version: '3.4'

x-labels:
  &default-labels
  org.supernetworks.ci: ${CI:-false}

x-logging:
  &default-logging
  driver: journald

services:
  base:
    container_name: superbase
    image: ghcr.io/spr-networks/super_base
    build: base
    network_mode: host
    privileged: true
    labels: *default-labels
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/
  dhcp:
    container_name: superdhcp
    image: ghcr.io/spr-networks/super_dhcp
    build: dhcp
    network_mode: host
    privileged: true
    depends_on:
      - "base"
    labels: *default-labels
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/
      - ./configs/dhcp/:/configs/dhcp/
      - ./configs/zones/:/configs/zones/
      - ./state/dhcp/:/state/dhcp/
      - /sys/fs/bpf:/sys/fs/bpf
  dhcp_client:
    container_name: superdhcp_client
    image: ghcr.io/spr-networks/super_dhcp_client
    build: dhcp
    network_mode: host
    privileged: true
    depends_on:
      - "base"
    labels: *default-labels
    logging: *default-logging
    entrypoint: /scripts/client.sh
    volumes:
      - ./configs/base/:/configs/base/
  dns:
    container_name: superdns
    image: ghcr.io/spr-networks/super_dns
    build: dns
    network_mode: host
    privileged: true
    labels: *default-labels
    logging: *default-logging
    depends_on:
      - "base"
    volumes:
      - ./configs/base/:/configs/base/
      - ./configs/dns/:/configs/dns/
      - ./state/dns/:/state/dns/
      - ./state/public/:/state/public/:ro
  wifid:
    container_name: superwifid
    image: ghcr.io/spr-networks/super_wifid
    build: wifid
    network_mode: host
    privileged: true
    labels: *default-labels
    logging: *default-logging
    depends_on:
      - "dhcp"
      - "dns"
      - "multicast_udp_proxy"
    volumes:
      - ./configs/base/:/configs/base/
      - ./configs/wifi/:/configs/wifi/
      - ./state/wifi/:/state/wifi/
  multicast_udp_proxy:
    container_name: super_multicast_udp_proxy
    image: ghcr.io/spr-networks/super_multicast_udp_proxy
    build: multicast_udp_proxy
    network_mode: host
    privileged: true
    depends_on:
      - "base"
    labels: *default-labels
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/
      - ./state/public/:/state/public/:ro
  ppp:
    container_name: superppp
    image: ghcr.io/spr-networks/super_ppp
    build: ppp
    network_mode: host
    privileged: true
    depends_on:
      - "base"
    labels: *default-labels
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/
      - ./configs/ppp/:/etc/ppp/
  wireguard:
    container_name: superwireguard
    image: ghcr.io/spr-networks/super_wireguard
    build: wireguard
    network_mode: host
    privileged: true
    depends_on:
      - "base"
      - "dhcp"
      - "api"
    labels: *default-labels
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/
      - ./configs/wireguard/:/configs/wireguard/
      - ./state/plugins/wireguard/:/state/plugins/wireguard/
      - ./state/dhcp/:/state/dhcp/
  frontend:
    container_name: superfrontend
    image: ghcr.io/spr-networks/super_frontend
    entrypoint: ["cp", "-RT", "/build/", "/frontend/build"]
    build: frontend
    network_mode: none
    volumes:
      - ./frontend/:/frontend
  api:
    container_name: superapi
    image: ghcr.io/spr-networks/super_api
    build: api
    network_mode: host
    privileged: true
    restart: always
    depends_on:
      - "base"
      - "wifid"
      - "dhcp"
      - "frontend"
    labels: *default-labels
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/
      - ./configs/devices/:/configs/devices/
      - ./configs/zones/:/configs/zones/
      - ./configs/wifi/:/configs/wifi/
      - ./configs/wireguard/:/configs/wireguard/
      - ./configs/scripts/:/configs/scripts/
      - ./state/wifi/:/state/wifi/
      - ./state/dhcp/:/state/dhcp/
      - ./state/dns/:/state/dns/
      - ./state/api/:/state/api/
      - ./state/plugins/:/state/plugins/
      - ./state/public/:/state/public/
      - ./frontend/build:/ui/
      - /var/log/journal:/var/log/journal:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  plugin-lookup:
    container_name: super-plugin-lookup
    image: ghcr.io/spr-networks/super_plugin-lookup
    build: plugin-lookup
    network_mode: host
    labels: *default-labels
    logging: *default-logging
    depends_on:
      - "base"
      - "dns"
    volumes:
      - ./state/plugins/plugin-lookup/:/state/plugins/plugin-lookup/
  dyndns:
    container_name: superdyndns
    image: ghcr.io/spr-networks/super_dyndns
    build: dyndns
    network_mode: bridge
    labels: *default-labels
    logging: *default-logging
    depends_on:
      - "base"
      - "dns"
    volumes:
      - ./state/plugins/dyndns/:/state/plugins/dyndns
      - ./configs/dyndns/:/configs/dyndns
